# -*- coding: utf-8 -*-
# File generated from our OpenAPI spec
from importlib import import_module
from typing_extensions import TYPE_CHECKING

if TYPE_CHECKING:
    from stripe.params.checkout._session_create_params import (
        SessionCreateParams as SessionCreateParams,
        SessionCreateParamsAdaptivePricing as SessionCreateParamsAdaptivePricing,
        SessionCreateParamsAfterExpiration as SessionCreateParamsAfterExpiration,
        SessionCreateParamsAfterExpirationRecovery as SessionCreateParamsAfterExpirationRecovery,
        SessionCreateParamsAutomaticTax as SessionCreateParamsAutomaticTax,
        SessionCreateParamsAutomaticTaxLiability as SessionCreateParamsAutomaticTaxLiability,
        SessionCreateParamsBrandingSettings as SessionCreateParamsBrandingSettings,
        SessionCreateParamsBrandingSettingsIcon as SessionCreateParamsBrandingSettingsIcon,
        SessionCreateParamsBrandingSettingsLogo as SessionCreateParamsBrandingSettingsLogo,
        SessionCreateParamsConsentCollection as SessionCreateParamsConsentCollection,
        SessionCreateParamsConsentCollectionPaymentMethodReuseAgreement as SessionCreateParamsConsentCollectionPaymentMethodReuseAgreement,
        SessionCreateParamsCustomField as SessionCreateParamsCustomField,
        SessionCreateParamsCustomFieldDropdown as SessionCreateParamsCustomFieldDropdown,
        SessionCreateParamsCustomFieldDropdownOption as SessionCreateParamsCustomFieldDropdownOption,
        SessionCreateParamsCustomFieldLabel as SessionCreateParamsCustomFieldLabel,
        SessionCreateParamsCustomFieldNumeric as SessionCreateParamsCustomFieldNumeric,
        SessionCreateParamsCustomFieldText as SessionCreateParamsCustomFieldText,
        SessionCreateParamsCustomText as SessionCreateParamsCustomText,
        SessionCreateParamsCustomTextAfterSubmit as SessionCreateParamsCustomTextAfterSubmit,
        SessionCreateParamsCustomTextShippingAddress as SessionCreateParamsCustomTextShippingAddress,
        SessionCreateParamsCustomTextSubmit as SessionCreateParamsCustomTextSubmit,
        SessionCreateParamsCustomTextTermsOfServiceAcceptance as SessionCreateParamsCustomTextTermsOfServiceAcceptance,
        SessionCreateParamsCustomerUpdate as SessionCreateParamsCustomerUpdate,
        SessionCreateParamsDiscount as SessionCreateParamsDiscount,
        SessionCreateParamsInvoiceCreation as SessionCreateParamsInvoiceCreation,
        SessionCreateParamsInvoiceCreationInvoiceData as SessionCreateParamsInvoiceCreationInvoiceData,
        SessionCreateParamsInvoiceCreationInvoiceDataCustomField as SessionCreateParamsInvoiceCreationInvoiceDataCustomField,
        SessionCreateParamsInvoiceCreationInvoiceDataIssuer as SessionCreateParamsInvoiceCreationInvoiceDataIssuer,
        SessionCreateParamsInvoiceCreationInvoiceDataRenderingOptions as SessionCreateParamsInvoiceCreationInvoiceDataRenderingOptions,
        SessionCreateParamsLineItem as SessionCreateParamsLineItem,
        SessionCreateParamsLineItemAdjustableQuantity as SessionCreateParamsLineItemAdjustableQuantity,
        SessionCreateParamsLineItemPriceData as SessionCreateParamsLineItemPriceData,
        SessionCreateParamsLineItemPriceDataProductData as SessionCreateParamsLineItemPriceDataProductData,
        SessionCreateParamsLineItemPriceDataRecurring as SessionCreateParamsLineItemPriceDataRecurring,
        SessionCreateParamsNameCollection as SessionCreateParamsNameCollection,
        SessionCreateParamsNameCollectionBusiness as SessionCreateParamsNameCollectionBusiness,
        SessionCreateParamsNameCollectionIndividual as SessionCreateParamsNameCollectionIndividual,
        SessionCreateParamsOptionalItem as SessionCreateParamsOptionalItem,
        SessionCreateParamsOptionalItemAdjustableQuantity as SessionCreateParamsOptionalItemAdjustableQuantity,
        SessionCreateParamsPaymentIntentData as SessionCreateParamsPaymentIntentData,
        SessionCreateParamsPaymentIntentDataShipping as SessionCreateParamsPaymentIntentDataShipping,
        SessionCreateParamsPaymentIntentDataShippingAddress as SessionCreateParamsPaymentIntentDataShippingAddress,
        SessionCreateParamsPaymentIntentDataTransferData as SessionCreateParamsPaymentIntentDataTransferData,
        SessionCreateParamsPaymentMethodData as SessionCreateParamsPaymentMethodData,
        SessionCreateParamsPaymentMethodOptions as SessionCreateParamsPaymentMethodOptions,
        SessionCreateParamsPaymentMethodOptionsAcssDebit as SessionCreateParamsPaymentMethodOptionsAcssDebit,
        SessionCreateParamsPaymentMethodOptionsAcssDebitMandateOptions as SessionCreateParamsPaymentMethodOptionsAcssDebitMandateOptions,
        SessionCreateParamsPaymentMethodOptionsAffirm as SessionCreateParamsPaymentMethodOptionsAffirm,
        SessionCreateParamsPaymentMethodOptionsAfterpayClearpay as SessionCreateParamsPaymentMethodOptionsAfterpayClearpay,
        SessionCreateParamsPaymentMethodOptionsAlipay as SessionCreateParamsPaymentMethodOptionsAlipay,
        SessionCreateParamsPaymentMethodOptionsAlma as SessionCreateParamsPaymentMethodOptionsAlma,
        SessionCreateParamsPaymentMethodOptionsAmazonPay as SessionCreateParamsPaymentMethodOptionsAmazonPay,
        SessionCreateParamsPaymentMethodOptionsAuBecsDebit as SessionCreateParamsPaymentMethodOptionsAuBecsDebit,
        SessionCreateParamsPaymentMethodOptionsBacsDebit as SessionCreateParamsPaymentMethodOptionsBacsDebit,
        SessionCreateParamsPaymentMethodOptionsBacsDebitMandateOptions as SessionCreateParamsPaymentMethodOptionsBacsDebitMandateOptions,
        SessionCreateParamsPaymentMethodOptionsBancontact as SessionCreateParamsPaymentMethodOptionsBancontact,
        SessionCreateParamsPaymentMethodOptionsBillie as SessionCreateParamsPaymentMethodOptionsBillie,
        SessionCreateParamsPaymentMethodOptionsBoleto as SessionCreateParamsPaymentMethodOptionsBoleto,
        SessionCreateParamsPaymentMethodOptionsCard as SessionCreateParamsPaymentMethodOptionsCard,
        SessionCreateParamsPaymentMethodOptionsCardInstallments as SessionCreateParamsPaymentMethodOptionsCardInstallments,
        SessionCreateParamsPaymentMethodOptionsCardRestrictions as SessionCreateParamsPaymentMethodOptionsCardRestrictions,
        SessionCreateParamsPaymentMethodOptionsCashapp as SessionCreateParamsPaymentMethodOptionsCashapp,
        SessionCreateParamsPaymentMethodOptionsCustomerBalance as SessionCreateParamsPaymentMethodOptionsCustomerBalance,
        SessionCreateParamsPaymentMethodOptionsCustomerBalanceBankTransfer as SessionCreateParamsPaymentMethodOptionsCustomerBalanceBankTransfer,
        SessionCreateParamsPaymentMethodOptionsCustomerBalanceBankTransferEuBankTransfer as SessionCreateParamsPaymentMethodOptionsCustomerBalanceBankTransferEuBankTransfer,
        SessionCreateParamsPaymentMethodOptionsDemoPay as SessionCreateParamsPaymentMethodOptionsDemoPay,
        SessionCreateParamsPaymentMethodOptionsEps as SessionCreateParamsPaymentMethodOptionsEps,
        SessionCreateParamsPaymentMethodOptionsFpx as SessionCreateParamsPaymentMethodOptionsFpx,
        SessionCreateParamsPaymentMethodOptionsGiropay as SessionCreateParamsPaymentMethodOptionsGiropay,
        SessionCreateParamsPaymentMethodOptionsGrabpay as SessionCreateParamsPaymentMethodOptionsGrabpay,
        SessionCreateParamsPaymentMethodOptionsIdeal as SessionCreateParamsPaymentMethodOptionsIdeal,
        SessionCreateParamsPaymentMethodOptionsKakaoPay as SessionCreateParamsPaymentMethodOptionsKakaoPay,
        SessionCreateParamsPaymentMethodOptionsKlarna as SessionCreateParamsPaymentMethodOptionsKlarna,
        SessionCreateParamsPaymentMethodOptionsKlarnaSubscription as SessionCreateParamsPaymentMethodOptionsKlarnaSubscription,
        SessionCreateParamsPaymentMethodOptionsKlarnaSubscriptionNextBilling as SessionCreateParamsPaymentMethodOptionsKlarnaSubscriptionNextBilling,
        SessionCreateParamsPaymentMethodOptionsKonbini as SessionCreateParamsPaymentMethodOptionsKonbini,
        SessionCreateParamsPaymentMethodOptionsKrCard as SessionCreateParamsPaymentMethodOptionsKrCard,
        SessionCreateParamsPaymentMethodOptionsLink as SessionCreateParamsPaymentMethodOptionsLink,
        SessionCreateParamsPaymentMethodOptionsMobilepay as SessionCreateParamsPaymentMethodOptionsMobilepay,
        SessionCreateParamsPaymentMethodOptionsMultibanco as SessionCreateParamsPaymentMethodOptionsMultibanco,
        SessionCreateParamsPaymentMethodOptionsNaverPay as SessionCreateParamsPaymentMethodOptionsNaverPay,
        SessionCreateParamsPaymentMethodOptionsOxxo as SessionCreateParamsPaymentMethodOptionsOxxo,
        SessionCreateParamsPaymentMethodOptionsP24 as SessionCreateParamsPaymentMethodOptionsP24,
        SessionCreateParamsPaymentMethodOptionsPayByBank as SessionCreateParamsPaymentMethodOptionsPayByBank,
        SessionCreateParamsPaymentMethodOptionsPayco as SessionCreateParamsPaymentMethodOptionsPayco,
        SessionCreateParamsPaymentMethodOptionsPaynow as SessionCreateParamsPaymentMethodOptionsPaynow,
        SessionCreateParamsPaymentMethodOptionsPaypal as SessionCreateParamsPaymentMethodOptionsPaypal,
        SessionCreateParamsPaymentMethodOptionsPix as SessionCreateParamsPaymentMethodOptionsPix,
        SessionCreateParamsPaymentMethodOptionsRevolutPay as SessionCreateParamsPaymentMethodOptionsRevolutPay,
        SessionCreateParamsPaymentMethodOptionsSamsungPay as SessionCreateParamsPaymentMethodOptionsSamsungPay,
        SessionCreateParamsPaymentMethodOptionsSatispay as SessionCreateParamsPaymentMethodOptionsSatispay,
        SessionCreateParamsPaymentMethodOptionsSepaDebit as SessionCreateParamsPaymentMethodOptionsSepaDebit,
        SessionCreateParamsPaymentMethodOptionsSepaDebitMandateOptions as SessionCreateParamsPaymentMethodOptionsSepaDebitMandateOptions,
        SessionCreateParamsPaymentMethodOptionsSofort as SessionCreateParamsPaymentMethodOptionsSofort,
        SessionCreateParamsPaymentMethodOptionsSwish as SessionCreateParamsPaymentMethodOptionsSwish,
        SessionCreateParamsPaymentMethodOptionsUsBankAccount as SessionCreateParamsPaymentMethodOptionsUsBankAccount,
        SessionCreateParamsPaymentMethodOptionsUsBankAccountFinancialConnections as SessionCreateParamsPaymentMethodOptionsUsBankAccountFinancialConnections,
        SessionCreateParamsPaymentMethodOptionsWechatPay as SessionCreateParamsPaymentMethodOptionsWechatPay,
        SessionCreateParamsPermissions as SessionCreateParamsPermissions,
        SessionCreateParamsPhoneNumberCollection as SessionCreateParamsPhoneNumberCollection,
        SessionCreateParamsSavedPaymentMethodOptions as SessionCreateParamsSavedPaymentMethodOptions,
        SessionCreateParamsSetupIntentData as SessionCreateParamsSetupIntentData,
        SessionCreateParamsShippingAddressCollection as SessionCreateParamsShippingAddressCollection,
        SessionCreateParamsShippingOption as SessionCreateParamsShippingOption,
        SessionCreateParamsShippingOptionShippingRateData as SessionCreateParamsShippingOptionShippingRateData,
        SessionCreateParamsShippingOptionShippingRateDataDeliveryEstimate as SessionCreateParamsShippingOptionShippingRateDataDeliveryEstimate,
        SessionCreateParamsShippingOptionShippingRateDataDeliveryEstimateMaximum as SessionCreateParamsShippingOptionShippingRateDataDeliveryEstimateMaximum,
        SessionCreateParamsShippingOptionShippingRateDataDeliveryEstimateMinimum as SessionCreateParamsShippingOptionShippingRateDataDeliveryEstimateMinimum,
        SessionCreateParamsShippingOptionShippingRateDataFixedAmount as SessionCreateParamsShippingOptionShippingRateDataFixedAmount,
        SessionCreateParamsShippingOptionShippingRateDataFixedAmountCurrencyOptions as SessionCreateParamsShippingOptionShippingRateDataFixedAmountCurrencyOptions,
        SessionCreateParamsSubscriptionData as SessionCreateParamsSubscriptionData,
        SessionCreateParamsSubscriptionDataBillingMode as SessionCreateParamsSubscriptionDataBillingMode,
        SessionCreateParamsSubscriptionDataBillingModeFlexible as SessionCreateParamsSubscriptionDataBillingModeFlexible,
        SessionCreateParamsSubscriptionDataInvoiceSettings as SessionCreateParamsSubscriptionDataInvoiceSettings,
        SessionCreateParamsSubscriptionDataInvoiceSettingsIssuer as SessionCreateParamsSubscriptionDataInvoiceSettingsIssuer,
        SessionCreateParamsSubscriptionDataTransferData as SessionCreateParamsSubscriptionDataTransferData,
        SessionCreateParamsSubscriptionDataTrialSettings as SessionCreateParamsSubscriptionDataTrialSettings,
        SessionCreateParamsSubscriptionDataTrialSettingsEndBehavior as SessionCreateParamsSubscriptionDataTrialSettingsEndBehavior,
        SessionCreateParamsTaxIdCollection as SessionCreateParamsTaxIdCollection,
        SessionCreateParamsWalletOptions as SessionCreateParamsWalletOptions,
        SessionCreateParamsWalletOptionsLink as SessionCreateParamsWalletOptionsLink,
    )
    from stripe.params.checkout._session_expire_params import (
        SessionExpireParams as SessionExpireParams,
    )
    from stripe.params.checkout._session_line_item_list_params import (
        SessionLineItemListParams as SessionLineItemListParams,
    )
    from stripe.params.checkout._session_list_line_items_params import (
        SessionListLineItemsParams as SessionListLineItemsParams,
    )
    from stripe.params.checkout._session_list_params import (
        SessionListParams as SessionListParams,
        SessionListParamsCreated as SessionListParamsCreated,
        SessionListParamsCustomerDetails as SessionListParamsCustomerDetails,
    )
    from stripe.params.checkout._session_modify_params import (
        SessionModifyParams as SessionModifyParams,
        SessionModifyParamsCollectedInformation as SessionModifyParamsCollectedInformation,
        SessionModifyParamsCollectedInformationShippingDetails as SessionModifyParamsCollectedInformationShippingDetails,
        SessionModifyParamsCollectedInformationShippingDetailsAddress as SessionModifyParamsCollectedInformationShippingDetailsAddress,
        SessionModifyParamsShippingOption as SessionModifyParamsShippingOption,
        SessionModifyParamsShippingOptionShippingRateData as SessionModifyParamsShippingOptionShippingRateData,
        SessionModifyParamsShippingOptionShippingRateDataDeliveryEstimate as SessionModifyParamsShippingOptionShippingRateDataDeliveryEstimate,
        SessionModifyParamsShippingOptionShippingRateDataDeliveryEstimateMaximum as SessionModifyParamsShippingOptionShippingRateDataDeliveryEstimateMaximum,
        SessionModifyParamsShippingOptionShippingRateDataDeliveryEstimateMinimum as SessionModifyParamsShippingOptionShippingRateDataDeliveryEstimateMinimum,
        SessionModifyParamsShippingOptionShippingRateDataFixedAmount as SessionModifyParamsShippingOptionShippingRateDataFixedAmount,
        SessionModifyParamsShippingOptionShippingRateDataFixedAmountCurrencyOptions as SessionModifyParamsShippingOptionShippingRateDataFixedAmountCurrencyOptions,
    )
    from stripe.params.checkout._session_retrieve_params import (
        SessionRetrieveParams as SessionRetrieveParams,
    )
    from stripe.params.checkout._session_update_params import (
        SessionUpdateParams as SessionUpdateParams,
        SessionUpdateParamsCollectedInformation as SessionUpdateParamsCollectedInformation,
        SessionUpdateParamsCollectedInformationShippingDetails as SessionUpdateParamsCollectedInformationShippingDetails,
        SessionUpdateParamsCollectedInformationShippingDetailsAddress as SessionUpdateParamsCollectedInformationShippingDetailsAddress,
        SessionUpdateParamsShippingOption as SessionUpdateParamsShippingOption,
        SessionUpdateParamsShippingOptionShippingRateData as SessionUpdateParamsShippingOptionShippingRateData,
        SessionUpdateParamsShippingOptionShippingRateDataDeliveryEstimate as SessionUpdateParamsShippingOptionShippingRateDataDeliveryEstimate,
        SessionUpdateParamsShippingOptionShippingRateDataDeliveryEstimateMaximum as SessionUpdateParamsShippingOptionShippingRateDataDeliveryEstimateMaximum,
        SessionUpdateParamsShippingOptionShippingRateDataDeliveryEstimateMinimum as SessionUpdateParamsShippingOptionShippingRateDataDeliveryEstimateMinimum,
        SessionUpdateParamsShippingOptionShippingRateDataFixedAmount as SessionUpdateParamsShippingOptionShippingRateDataFixedAmount,
        SessionUpdateParamsShippingOptionShippingRateDataFixedAmountCurrencyOptions as SessionUpdateParamsShippingOptionShippingRateDataFixedAmountCurrencyOptions,
    )

_submodules = {
    "SessionCreateParams": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsAdaptivePricing": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsAfterExpiration": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsAfterExpirationRecovery": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsAutomaticTax": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsAutomaticTaxLiability": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsBrandingSettings": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsBrandingSettingsIcon": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsBrandingSettingsLogo": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsConsentCollection": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsConsentCollectionPaymentMethodReuseAgreement": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsCustomField": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsCustomFieldDropdown": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsCustomFieldDropdownOption": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsCustomFieldLabel": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsCustomFieldNumeric": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsCustomFieldText": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsCustomText": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsCustomTextAfterSubmit": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsCustomTextShippingAddress": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsCustomTextSubmit": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsCustomTextTermsOfServiceAcceptance": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsCustomerUpdate": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsDiscount": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsInvoiceCreation": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsInvoiceCreationInvoiceData": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsInvoiceCreationInvoiceDataCustomField": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsInvoiceCreationInvoiceDataIssuer": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsInvoiceCreationInvoiceDataRenderingOptions": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsLineItem": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsLineItemAdjustableQuantity": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsLineItemPriceData": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsLineItemPriceDataProductData": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsLineItemPriceDataRecurring": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsNameCollection": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsNameCollectionBusiness": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsNameCollectionIndividual": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsOptionalItem": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsOptionalItemAdjustableQuantity": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentIntentData": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentIntentDataShipping": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentIntentDataShippingAddress": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentIntentDataTransferData": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodData": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptions": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsAcssDebit": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsAcssDebitMandateOptions": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsAffirm": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsAfterpayClearpay": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsAlipay": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsAlma": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsAmazonPay": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsAuBecsDebit": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsBacsDebit": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsBacsDebitMandateOptions": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsBancontact": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsBillie": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsBoleto": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsCard": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsCardInstallments": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsCardRestrictions": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsCashapp": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsCustomerBalance": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsCustomerBalanceBankTransfer": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsCustomerBalanceBankTransferEuBankTransfer": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsDemoPay": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsEps": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsFpx": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsGiropay": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsGrabpay": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsIdeal": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsKakaoPay": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsKlarna": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsKlarnaSubscription": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsKlarnaSubscriptionNextBilling": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsKonbini": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsKrCard": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsLink": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsMobilepay": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsMultibanco": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsNaverPay": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsOxxo": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsP24": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsPayByBank": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsPayco": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsPaynow": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsPaypal": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsPix": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsRevolutPay": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsSamsungPay": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsSatispay": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsSepaDebit": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsSepaDebitMandateOptions": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsSofort": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsSwish": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsUsBankAccount": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsUsBankAccountFinancialConnections": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPaymentMethodOptionsWechatPay": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPermissions": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsPhoneNumberCollection": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsSavedPaymentMethodOptions": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsSetupIntentData": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsShippingAddressCollection": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsShippingOption": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsShippingOptionShippingRateData": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsShippingOptionShippingRateDataDeliveryEstimate": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsShippingOptionShippingRateDataDeliveryEstimateMaximum": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsShippingOptionShippingRateDataDeliveryEstimateMinimum": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsShippingOptionShippingRateDataFixedAmount": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsShippingOptionShippingRateDataFixedAmountCurrencyOptions": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsSubscriptionData": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsSubscriptionDataBillingMode": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsSubscriptionDataBillingModeFlexible": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsSubscriptionDataInvoiceSettings": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsSubscriptionDataInvoiceSettingsIssuer": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsSubscriptionDataTransferData": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsSubscriptionDataTrialSettings": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsSubscriptionDataTrialSettingsEndBehavior": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsTaxIdCollection": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsWalletOptions": "stripe.params.checkout._session_create_params",
    "SessionCreateParamsWalletOptionsLink": "stripe.params.checkout._session_create_params",
    "SessionExpireParams": "stripe.params.checkout._session_expire_params",
    "SessionLineItemListParams": "stripe.params.checkout._session_line_item_list_params",
    "SessionListLineItemsParams": "stripe.params.checkout._session_list_line_items_params",
    "SessionListParams": "stripe.params.checkout._session_list_params",
    "SessionListParamsCreated": "stripe.params.checkout._session_list_params",
    "SessionListParamsCustomerDetails": "stripe.params.checkout._session_list_params",
    "SessionModifyParams": "stripe.params.checkout._session_modify_params",
    "SessionModifyParamsCollectedInformation": "stripe.params.checkout._session_modify_params",
    "SessionModifyParamsCollectedInformationShippingDetails": "stripe.params.checkout._session_modify_params",
    "SessionModifyParamsCollectedInformationShippingDetailsAddress": "stripe.params.checkout._session_modify_params",
    "SessionModifyParamsShippingOption": "stripe.params.checkout._session_modify_params",
    "SessionModifyParamsShippingOptionShippingRateData": "stripe.params.checkout._session_modify_params",
    "SessionModifyParamsShippingOptionShippingRateDataDeliveryEstimate": "stripe.params.checkout._session_modify_params",
    "SessionModifyParamsShippingOptionShippingRateDataDeliveryEstimateMaximum": "stripe.params.checkout._session_modify_params",
    "SessionModifyParamsShippingOptionShippingRateDataDeliveryEstimateMinimum": "stripe.params.checkout._session_modify_params",
    "SessionModifyParamsShippingOptionShippingRateDataFixedAmount": "stripe.params.checkout._session_modify_params",
    "SessionModifyParamsShippingOptionShippingRateDataFixedAmountCurrencyOptions": "stripe.params.checkout._session_modify_params",
    "SessionRetrieveParams": "stripe.params.checkout._session_retrieve_params",
    "SessionUpdateParams": "stripe.params.checkout._session_update_params",
    "SessionUpdateParamsCollectedInformation": "stripe.params.checkout._session_update_params",
    "SessionUpdateParamsCollectedInformationShippingDetails": "stripe.params.checkout._session_update_params",
    "SessionUpdateParamsCollectedInformationShippingDetailsAddress": "stripe.params.checkout._session_update_params",
    "SessionUpdateParamsShippingOption": "stripe.params.checkout._session_update_params",
    "SessionUpdateParamsShippingOptionShippingRateData": "stripe.params.checkout._session_update_params",
    "SessionUpdateParamsShippingOptionShippingRateDataDeliveryEstimate": "stripe.params.checkout._session_update_params",
    "SessionUpdateParamsShippingOptionShippingRateDataDeliveryEstimateMaximum": "stripe.params.checkout._session_update_params",
    "SessionUpdateParamsShippingOptionShippingRateDataDeliveryEstimateMinimum": "stripe.params.checkout._session_update_params",
    "SessionUpdateParamsShippingOptionShippingRateDataFixedAmount": "stripe.params.checkout._session_update_params",
    "SessionUpdateParamsShippingOptionShippingRateDataFixedAmountCurrencyOptions": "stripe.params.checkout._session_update_params",
}
if not TYPE_CHECKING:

    def __getattr__(name):
        try:
            return getattr(
                import_module(_submodules[name]),
                name,
            )
        except KeyError:
            raise AttributeError(f"cannot import '{name}' from '{__name__}'")
