# -*- coding: utf-8 -*-
# File generated from our OpenAPI spec
from importlib import import_module
from typing_extensions import TYPE_CHECKING

if TYPE_CHECKING:
    from stripe.params.tax._calculation_create_params import (
        CalculationCreateParams as CalculationCreateParams,
        CalculationCreateParamsCustomerDetails as CalculationCreateParamsCustomerDetails,
        CalculationCreateParamsCustomerDetailsAddress as CalculationCreateParamsCustomerDetailsAddress,
        CalculationCreateParamsCustomerDetailsTaxId as CalculationCreateParamsCustomerDetailsTaxId,
        CalculationCreateParamsLineItem as CalculationCreateParamsLineItem,
        CalculationCreateParamsShipFromDetails as CalculationCreateParamsShipFromDetails,
        CalculationCreateParamsShipFromDetailsAddress as CalculationCreateParamsShipFromDetailsAddress,
        CalculationCreateParamsShippingCost as CalculationCreateParamsShippingCost,
    )
    from stripe.params.tax._calculation_line_item_list_params import (
        CalculationLineItemListParams as CalculationLineItemListParams,
    )
    from stripe.params.tax._calculation_list_line_items_params import (
        CalculationListLineItemsParams as CalculationListLineItemsParams,
    )
    from stripe.params.tax._calculation_retrieve_params import (
        CalculationRetrieveParams as CalculationRetrieveParams,
    )
    from stripe.params.tax._registration_create_params import (
        RegistrationCreateParams as RegistrationCreateParams,
        RegistrationCreateParamsCountryOptions as RegistrationCreateParamsCountryOptions,
        RegistrationCreateParamsCountryOptionsAe as RegistrationCreateParamsCountryOptionsAe,
        RegistrationCreateParamsCountryOptionsAeStandard as RegistrationCreateParamsCountryOptionsAeStandard,
        RegistrationCreateParamsCountryOptionsAl as RegistrationCreateParamsCountryOptionsAl,
        RegistrationCreateParamsCountryOptionsAlStandard as RegistrationCreateParamsCountryOptionsAlStandard,
        RegistrationCreateParamsCountryOptionsAm as RegistrationCreateParamsCountryOptionsAm,
        RegistrationCreateParamsCountryOptionsAo as RegistrationCreateParamsCountryOptionsAo,
        RegistrationCreateParamsCountryOptionsAoStandard as RegistrationCreateParamsCountryOptionsAoStandard,
        RegistrationCreateParamsCountryOptionsAt as RegistrationCreateParamsCountryOptionsAt,
        RegistrationCreateParamsCountryOptionsAtStandard as RegistrationCreateParamsCountryOptionsAtStandard,
        RegistrationCreateParamsCountryOptionsAu as RegistrationCreateParamsCountryOptionsAu,
        RegistrationCreateParamsCountryOptionsAuStandard as RegistrationCreateParamsCountryOptionsAuStandard,
        RegistrationCreateParamsCountryOptionsAw as RegistrationCreateParamsCountryOptionsAw,
        RegistrationCreateParamsCountryOptionsAwStandard as RegistrationCreateParamsCountryOptionsAwStandard,
        RegistrationCreateParamsCountryOptionsAz as RegistrationCreateParamsCountryOptionsAz,
        RegistrationCreateParamsCountryOptionsBa as RegistrationCreateParamsCountryOptionsBa,
        RegistrationCreateParamsCountryOptionsBaStandard as RegistrationCreateParamsCountryOptionsBaStandard,
        RegistrationCreateParamsCountryOptionsBb as RegistrationCreateParamsCountryOptionsBb,
        RegistrationCreateParamsCountryOptionsBbStandard as RegistrationCreateParamsCountryOptionsBbStandard,
        RegistrationCreateParamsCountryOptionsBd as RegistrationCreateParamsCountryOptionsBd,
        RegistrationCreateParamsCountryOptionsBdStandard as RegistrationCreateParamsCountryOptionsBdStandard,
        RegistrationCreateParamsCountryOptionsBe as RegistrationCreateParamsCountryOptionsBe,
        RegistrationCreateParamsCountryOptionsBeStandard as RegistrationCreateParamsCountryOptionsBeStandard,
        RegistrationCreateParamsCountryOptionsBf as RegistrationCreateParamsCountryOptionsBf,
        RegistrationCreateParamsCountryOptionsBfStandard as RegistrationCreateParamsCountryOptionsBfStandard,
        RegistrationCreateParamsCountryOptionsBg as RegistrationCreateParamsCountryOptionsBg,
        RegistrationCreateParamsCountryOptionsBgStandard as RegistrationCreateParamsCountryOptionsBgStandard,
        RegistrationCreateParamsCountryOptionsBh as RegistrationCreateParamsCountryOptionsBh,
        RegistrationCreateParamsCountryOptionsBhStandard as RegistrationCreateParamsCountryOptionsBhStandard,
        RegistrationCreateParamsCountryOptionsBj as RegistrationCreateParamsCountryOptionsBj,
        RegistrationCreateParamsCountryOptionsBs as RegistrationCreateParamsCountryOptionsBs,
        RegistrationCreateParamsCountryOptionsBsStandard as RegistrationCreateParamsCountryOptionsBsStandard,
        RegistrationCreateParamsCountryOptionsBy as RegistrationCreateParamsCountryOptionsBy,
        RegistrationCreateParamsCountryOptionsCa as RegistrationCreateParamsCountryOptionsCa,
        RegistrationCreateParamsCountryOptionsCaProvinceStandard as RegistrationCreateParamsCountryOptionsCaProvinceStandard,
        RegistrationCreateParamsCountryOptionsCd as RegistrationCreateParamsCountryOptionsCd,
        RegistrationCreateParamsCountryOptionsCdStandard as RegistrationCreateParamsCountryOptionsCdStandard,
        RegistrationCreateParamsCountryOptionsCh as RegistrationCreateParamsCountryOptionsCh,
        RegistrationCreateParamsCountryOptionsChStandard as RegistrationCreateParamsCountryOptionsChStandard,
        RegistrationCreateParamsCountryOptionsCl as RegistrationCreateParamsCountryOptionsCl,
        RegistrationCreateParamsCountryOptionsCm as RegistrationCreateParamsCountryOptionsCm,
        RegistrationCreateParamsCountryOptionsCo as RegistrationCreateParamsCountryOptionsCo,
        RegistrationCreateParamsCountryOptionsCr as RegistrationCreateParamsCountryOptionsCr,
        RegistrationCreateParamsCountryOptionsCv as RegistrationCreateParamsCountryOptionsCv,
        RegistrationCreateParamsCountryOptionsCy as RegistrationCreateParamsCountryOptionsCy,
        RegistrationCreateParamsCountryOptionsCyStandard as RegistrationCreateParamsCountryOptionsCyStandard,
        RegistrationCreateParamsCountryOptionsCz as RegistrationCreateParamsCountryOptionsCz,
        RegistrationCreateParamsCountryOptionsCzStandard as RegistrationCreateParamsCountryOptionsCzStandard,
        RegistrationCreateParamsCountryOptionsDe as RegistrationCreateParamsCountryOptionsDe,
        RegistrationCreateParamsCountryOptionsDeStandard as RegistrationCreateParamsCountryOptionsDeStandard,
        RegistrationCreateParamsCountryOptionsDk as RegistrationCreateParamsCountryOptionsDk,
        RegistrationCreateParamsCountryOptionsDkStandard as RegistrationCreateParamsCountryOptionsDkStandard,
        RegistrationCreateParamsCountryOptionsEc as RegistrationCreateParamsCountryOptionsEc,
        RegistrationCreateParamsCountryOptionsEe as RegistrationCreateParamsCountryOptionsEe,
        RegistrationCreateParamsCountryOptionsEeStandard as RegistrationCreateParamsCountryOptionsEeStandard,
        RegistrationCreateParamsCountryOptionsEg as RegistrationCreateParamsCountryOptionsEg,
        RegistrationCreateParamsCountryOptionsEs as RegistrationCreateParamsCountryOptionsEs,
        RegistrationCreateParamsCountryOptionsEsStandard as RegistrationCreateParamsCountryOptionsEsStandard,
        RegistrationCreateParamsCountryOptionsEt as RegistrationCreateParamsCountryOptionsEt,
        RegistrationCreateParamsCountryOptionsEtStandard as RegistrationCreateParamsCountryOptionsEtStandard,
        RegistrationCreateParamsCountryOptionsFi as RegistrationCreateParamsCountryOptionsFi,
        RegistrationCreateParamsCountryOptionsFiStandard as RegistrationCreateParamsCountryOptionsFiStandard,
        RegistrationCreateParamsCountryOptionsFr as RegistrationCreateParamsCountryOptionsFr,
        RegistrationCreateParamsCountryOptionsFrStandard as RegistrationCreateParamsCountryOptionsFrStandard,
        RegistrationCreateParamsCountryOptionsGb as RegistrationCreateParamsCountryOptionsGb,
        RegistrationCreateParamsCountryOptionsGbStandard as RegistrationCreateParamsCountryOptionsGbStandard,
        RegistrationCreateParamsCountryOptionsGe as RegistrationCreateParamsCountryOptionsGe,
        RegistrationCreateParamsCountryOptionsGn as RegistrationCreateParamsCountryOptionsGn,
        RegistrationCreateParamsCountryOptionsGnStandard as RegistrationCreateParamsCountryOptionsGnStandard,
        RegistrationCreateParamsCountryOptionsGr as RegistrationCreateParamsCountryOptionsGr,
        RegistrationCreateParamsCountryOptionsGrStandard as RegistrationCreateParamsCountryOptionsGrStandard,
        RegistrationCreateParamsCountryOptionsHr as RegistrationCreateParamsCountryOptionsHr,
        RegistrationCreateParamsCountryOptionsHrStandard as RegistrationCreateParamsCountryOptionsHrStandard,
        RegistrationCreateParamsCountryOptionsHu as RegistrationCreateParamsCountryOptionsHu,
        RegistrationCreateParamsCountryOptionsHuStandard as RegistrationCreateParamsCountryOptionsHuStandard,
        RegistrationCreateParamsCountryOptionsId as RegistrationCreateParamsCountryOptionsId,
        RegistrationCreateParamsCountryOptionsIe as RegistrationCreateParamsCountryOptionsIe,
        RegistrationCreateParamsCountryOptionsIeStandard as RegistrationCreateParamsCountryOptionsIeStandard,
        RegistrationCreateParamsCountryOptionsIn as RegistrationCreateParamsCountryOptionsIn,
        RegistrationCreateParamsCountryOptionsIs as RegistrationCreateParamsCountryOptionsIs,
        RegistrationCreateParamsCountryOptionsIsStandard as RegistrationCreateParamsCountryOptionsIsStandard,
        RegistrationCreateParamsCountryOptionsIt as RegistrationCreateParamsCountryOptionsIt,
        RegistrationCreateParamsCountryOptionsItStandard as RegistrationCreateParamsCountryOptionsItStandard,
        RegistrationCreateParamsCountryOptionsJp as RegistrationCreateParamsCountryOptionsJp,
        RegistrationCreateParamsCountryOptionsJpStandard as RegistrationCreateParamsCountryOptionsJpStandard,
        RegistrationCreateParamsCountryOptionsKe as RegistrationCreateParamsCountryOptionsKe,
        RegistrationCreateParamsCountryOptionsKg as RegistrationCreateParamsCountryOptionsKg,
        RegistrationCreateParamsCountryOptionsKh as RegistrationCreateParamsCountryOptionsKh,
        RegistrationCreateParamsCountryOptionsKr as RegistrationCreateParamsCountryOptionsKr,
        RegistrationCreateParamsCountryOptionsKz as RegistrationCreateParamsCountryOptionsKz,
        RegistrationCreateParamsCountryOptionsLa as RegistrationCreateParamsCountryOptionsLa,
        RegistrationCreateParamsCountryOptionsLt as RegistrationCreateParamsCountryOptionsLt,
        RegistrationCreateParamsCountryOptionsLtStandard as RegistrationCreateParamsCountryOptionsLtStandard,
        RegistrationCreateParamsCountryOptionsLu as RegistrationCreateParamsCountryOptionsLu,
        RegistrationCreateParamsCountryOptionsLuStandard as RegistrationCreateParamsCountryOptionsLuStandard,
        RegistrationCreateParamsCountryOptionsLv as RegistrationCreateParamsCountryOptionsLv,
        RegistrationCreateParamsCountryOptionsLvStandard as RegistrationCreateParamsCountryOptionsLvStandard,
        RegistrationCreateParamsCountryOptionsMa as RegistrationCreateParamsCountryOptionsMa,
        RegistrationCreateParamsCountryOptionsMd as RegistrationCreateParamsCountryOptionsMd,
        RegistrationCreateParamsCountryOptionsMe as RegistrationCreateParamsCountryOptionsMe,
        RegistrationCreateParamsCountryOptionsMeStandard as RegistrationCreateParamsCountryOptionsMeStandard,
        RegistrationCreateParamsCountryOptionsMk as RegistrationCreateParamsCountryOptionsMk,
        RegistrationCreateParamsCountryOptionsMkStandard as RegistrationCreateParamsCountryOptionsMkStandard,
        RegistrationCreateParamsCountryOptionsMr as RegistrationCreateParamsCountryOptionsMr,
        RegistrationCreateParamsCountryOptionsMrStandard as RegistrationCreateParamsCountryOptionsMrStandard,
        RegistrationCreateParamsCountryOptionsMt as RegistrationCreateParamsCountryOptionsMt,
        RegistrationCreateParamsCountryOptionsMtStandard as RegistrationCreateParamsCountryOptionsMtStandard,
        RegistrationCreateParamsCountryOptionsMx as RegistrationCreateParamsCountryOptionsMx,
        RegistrationCreateParamsCountryOptionsMy as RegistrationCreateParamsCountryOptionsMy,
        RegistrationCreateParamsCountryOptionsNg as RegistrationCreateParamsCountryOptionsNg,
        RegistrationCreateParamsCountryOptionsNl as RegistrationCreateParamsCountryOptionsNl,
        RegistrationCreateParamsCountryOptionsNlStandard as RegistrationCreateParamsCountryOptionsNlStandard,
        RegistrationCreateParamsCountryOptionsNo as RegistrationCreateParamsCountryOptionsNo,
        RegistrationCreateParamsCountryOptionsNoStandard as RegistrationCreateParamsCountryOptionsNoStandard,
        RegistrationCreateParamsCountryOptionsNp as RegistrationCreateParamsCountryOptionsNp,
        RegistrationCreateParamsCountryOptionsNz as RegistrationCreateParamsCountryOptionsNz,
        RegistrationCreateParamsCountryOptionsNzStandard as RegistrationCreateParamsCountryOptionsNzStandard,
        RegistrationCreateParamsCountryOptionsOm as RegistrationCreateParamsCountryOptionsOm,
        RegistrationCreateParamsCountryOptionsOmStandard as RegistrationCreateParamsCountryOptionsOmStandard,
        RegistrationCreateParamsCountryOptionsPe as RegistrationCreateParamsCountryOptionsPe,
        RegistrationCreateParamsCountryOptionsPh as RegistrationCreateParamsCountryOptionsPh,
        RegistrationCreateParamsCountryOptionsPl as RegistrationCreateParamsCountryOptionsPl,
        RegistrationCreateParamsCountryOptionsPlStandard as RegistrationCreateParamsCountryOptionsPlStandard,
        RegistrationCreateParamsCountryOptionsPt as RegistrationCreateParamsCountryOptionsPt,
        RegistrationCreateParamsCountryOptionsPtStandard as RegistrationCreateParamsCountryOptionsPtStandard,
        RegistrationCreateParamsCountryOptionsRo as RegistrationCreateParamsCountryOptionsRo,
        RegistrationCreateParamsCountryOptionsRoStandard as RegistrationCreateParamsCountryOptionsRoStandard,
        RegistrationCreateParamsCountryOptionsRs as RegistrationCreateParamsCountryOptionsRs,
        RegistrationCreateParamsCountryOptionsRsStandard as RegistrationCreateParamsCountryOptionsRsStandard,
        RegistrationCreateParamsCountryOptionsRu as RegistrationCreateParamsCountryOptionsRu,
        RegistrationCreateParamsCountryOptionsSa as RegistrationCreateParamsCountryOptionsSa,
        RegistrationCreateParamsCountryOptionsSe as RegistrationCreateParamsCountryOptionsSe,
        RegistrationCreateParamsCountryOptionsSeStandard as RegistrationCreateParamsCountryOptionsSeStandard,
        RegistrationCreateParamsCountryOptionsSg as RegistrationCreateParamsCountryOptionsSg,
        RegistrationCreateParamsCountryOptionsSgStandard as RegistrationCreateParamsCountryOptionsSgStandard,
        RegistrationCreateParamsCountryOptionsSi as RegistrationCreateParamsCountryOptionsSi,
        RegistrationCreateParamsCountryOptionsSiStandard as RegistrationCreateParamsCountryOptionsSiStandard,
        RegistrationCreateParamsCountryOptionsSk as RegistrationCreateParamsCountryOptionsSk,
        RegistrationCreateParamsCountryOptionsSkStandard as RegistrationCreateParamsCountryOptionsSkStandard,
        RegistrationCreateParamsCountryOptionsSn as RegistrationCreateParamsCountryOptionsSn,
        RegistrationCreateParamsCountryOptionsSr as RegistrationCreateParamsCountryOptionsSr,
        RegistrationCreateParamsCountryOptionsSrStandard as RegistrationCreateParamsCountryOptionsSrStandard,
        RegistrationCreateParamsCountryOptionsTh as RegistrationCreateParamsCountryOptionsTh,
        RegistrationCreateParamsCountryOptionsTj as RegistrationCreateParamsCountryOptionsTj,
        RegistrationCreateParamsCountryOptionsTr as RegistrationCreateParamsCountryOptionsTr,
        RegistrationCreateParamsCountryOptionsTz as RegistrationCreateParamsCountryOptionsTz,
        RegistrationCreateParamsCountryOptionsUa as RegistrationCreateParamsCountryOptionsUa,
        RegistrationCreateParamsCountryOptionsUg as RegistrationCreateParamsCountryOptionsUg,
        RegistrationCreateParamsCountryOptionsUs as RegistrationCreateParamsCountryOptionsUs,
        RegistrationCreateParamsCountryOptionsUsLocalAmusementTax as RegistrationCreateParamsCountryOptionsUsLocalAmusementTax,
        RegistrationCreateParamsCountryOptionsUsLocalLeaseTax as RegistrationCreateParamsCountryOptionsUsLocalLeaseTax,
        RegistrationCreateParamsCountryOptionsUsStateSalesTax as RegistrationCreateParamsCountryOptionsUsStateSalesTax,
        RegistrationCreateParamsCountryOptionsUsStateSalesTaxElection as RegistrationCreateParamsCountryOptionsUsStateSalesTaxElection,
        RegistrationCreateParamsCountryOptionsUy as RegistrationCreateParamsCountryOptionsUy,
        RegistrationCreateParamsCountryOptionsUyStandard as RegistrationCreateParamsCountryOptionsUyStandard,
        RegistrationCreateParamsCountryOptionsUz as RegistrationCreateParamsCountryOptionsUz,
        RegistrationCreateParamsCountryOptionsVn as RegistrationCreateParamsCountryOptionsVn,
        RegistrationCreateParamsCountryOptionsZa as RegistrationCreateParamsCountryOptionsZa,
        RegistrationCreateParamsCountryOptionsZaStandard as RegistrationCreateParamsCountryOptionsZaStandard,
        RegistrationCreateParamsCountryOptionsZm as RegistrationCreateParamsCountryOptionsZm,
        RegistrationCreateParamsCountryOptionsZw as RegistrationCreateParamsCountryOptionsZw,
        RegistrationCreateParamsCountryOptionsZwStandard as RegistrationCreateParamsCountryOptionsZwStandard,
    )
    from stripe.params.tax._registration_list_params import (
        RegistrationListParams as RegistrationListParams,
    )
    from stripe.params.tax._registration_modify_params import (
        RegistrationModifyParams as RegistrationModifyParams,
    )
    from stripe.params.tax._registration_retrieve_params import (
        RegistrationRetrieveParams as RegistrationRetrieveParams,
    )
    from stripe.params.tax._registration_update_params import (
        RegistrationUpdateParams as RegistrationUpdateParams,
    )
    from stripe.params.tax._settings_modify_params import (
        SettingsModifyParams as SettingsModifyParams,
        SettingsModifyParamsDefaults as SettingsModifyParamsDefaults,
        SettingsModifyParamsHeadOffice as SettingsModifyParamsHeadOffice,
        SettingsModifyParamsHeadOfficeAddress as SettingsModifyParamsHeadOfficeAddress,
    )
    from stripe.params.tax._settings_retrieve_params import (
        SettingsRetrieveParams as SettingsRetrieveParams,
    )
    from stripe.params.tax._settings_update_params import (
        SettingsUpdateParams as SettingsUpdateParams,
        SettingsUpdateParamsDefaults as SettingsUpdateParamsDefaults,
        SettingsUpdateParamsHeadOffice as SettingsUpdateParamsHeadOffice,
        SettingsUpdateParamsHeadOfficeAddress as SettingsUpdateParamsHeadOfficeAddress,
    )
    from stripe.params.tax._transaction_create_from_calculation_params import (
        TransactionCreateFromCalculationParams as TransactionCreateFromCalculationParams,
    )
    from stripe.params.tax._transaction_create_reversal_params import (
        TransactionCreateReversalParams as TransactionCreateReversalParams,
        TransactionCreateReversalParamsLineItem as TransactionCreateReversalParamsLineItem,
        TransactionCreateReversalParamsShippingCost as TransactionCreateReversalParamsShippingCost,
    )
    from stripe.params.tax._transaction_line_item_list_params import (
        TransactionLineItemListParams as TransactionLineItemListParams,
    )
    from stripe.params.tax._transaction_list_line_items_params import (
        TransactionListLineItemsParams as TransactionListLineItemsParams,
    )
    from stripe.params.tax._transaction_retrieve_params import (
        TransactionRetrieveParams as TransactionRetrieveParams,
    )

_submodules = {
    "CalculationCreateParams": "stripe.params.tax._calculation_create_params",
    "CalculationCreateParamsCustomerDetails": "stripe.params.tax._calculation_create_params",
    "CalculationCreateParamsCustomerDetailsAddress": "stripe.params.tax._calculation_create_params",
    "CalculationCreateParamsCustomerDetailsTaxId": "stripe.params.tax._calculation_create_params",
    "CalculationCreateParamsLineItem": "stripe.params.tax._calculation_create_params",
    "CalculationCreateParamsShipFromDetails": "stripe.params.tax._calculation_create_params",
    "CalculationCreateParamsShipFromDetailsAddress": "stripe.params.tax._calculation_create_params",
    "CalculationCreateParamsShippingCost": "stripe.params.tax._calculation_create_params",
    "CalculationLineItemListParams": "stripe.params.tax._calculation_line_item_list_params",
    "CalculationListLineItemsParams": "stripe.params.tax._calculation_list_line_items_params",
    "CalculationRetrieveParams": "stripe.params.tax._calculation_retrieve_params",
    "RegistrationCreateParams": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptions": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsAe": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsAeStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsAl": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsAlStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsAm": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsAo": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsAoStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsAt": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsAtStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsAu": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsAuStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsAw": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsAwStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsAz": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsBa": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsBaStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsBb": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsBbStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsBd": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsBdStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsBe": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsBeStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsBf": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsBfStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsBg": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsBgStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsBh": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsBhStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsBj": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsBs": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsBsStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsBy": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsCa": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsCaProvinceStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsCd": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsCdStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsCh": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsChStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsCl": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsCm": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsCo": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsCr": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsCv": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsCy": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsCyStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsCz": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsCzStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsDe": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsDeStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsDk": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsDkStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsEc": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsEe": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsEeStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsEg": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsEs": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsEsStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsEt": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsEtStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsFi": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsFiStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsFr": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsFrStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsGb": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsGbStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsGe": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsGn": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsGnStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsGr": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsGrStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsHr": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsHrStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsHu": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsHuStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsId": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsIe": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsIeStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsIn": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsIs": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsIsStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsIt": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsItStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsJp": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsJpStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsKe": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsKg": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsKh": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsKr": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsKz": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsLa": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsLt": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsLtStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsLu": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsLuStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsLv": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsLvStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsMa": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsMd": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsMe": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsMeStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsMk": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsMkStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsMr": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsMrStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsMt": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsMtStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsMx": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsMy": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsNg": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsNl": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsNlStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsNo": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsNoStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsNp": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsNz": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsNzStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsOm": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsOmStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsPe": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsPh": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsPl": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsPlStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsPt": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsPtStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsRo": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsRoStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsRs": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsRsStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsRu": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsSa": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsSe": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsSeStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsSg": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsSgStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsSi": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsSiStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsSk": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsSkStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsSn": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsSr": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsSrStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsTh": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsTj": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsTr": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsTz": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsUa": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsUg": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsUs": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsUsLocalAmusementTax": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsUsLocalLeaseTax": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsUsStateSalesTax": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsUsStateSalesTaxElection": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsUy": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsUyStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsUz": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsVn": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsZa": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsZaStandard": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsZm": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsZw": "stripe.params.tax._registration_create_params",
    "RegistrationCreateParamsCountryOptionsZwStandard": "stripe.params.tax._registration_create_params",
    "RegistrationListParams": "stripe.params.tax._registration_list_params",
    "RegistrationModifyParams": "stripe.params.tax._registration_modify_params",
    "RegistrationRetrieveParams": "stripe.params.tax._registration_retrieve_params",
    "RegistrationUpdateParams": "stripe.params.tax._registration_update_params",
    "SettingsModifyParams": "stripe.params.tax._settings_modify_params",
    "SettingsModifyParamsDefaults": "stripe.params.tax._settings_modify_params",
    "SettingsModifyParamsHeadOffice": "stripe.params.tax._settings_modify_params",
    "SettingsModifyParamsHeadOfficeAddress": "stripe.params.tax._settings_modify_params",
    "SettingsRetrieveParams": "stripe.params.tax._settings_retrieve_params",
    "SettingsUpdateParams": "stripe.params.tax._settings_update_params",
    "SettingsUpdateParamsDefaults": "stripe.params.tax._settings_update_params",
    "SettingsUpdateParamsHeadOffice": "stripe.params.tax._settings_update_params",
    "SettingsUpdateParamsHeadOfficeAddress": "stripe.params.tax._settings_update_params",
    "TransactionCreateFromCalculationParams": "stripe.params.tax._transaction_create_from_calculation_params",
    "TransactionCreateReversalParams": "stripe.params.tax._transaction_create_reversal_params",
    "TransactionCreateReversalParamsLineItem": "stripe.params.tax._transaction_create_reversal_params",
    "TransactionCreateReversalParamsShippingCost": "stripe.params.tax._transaction_create_reversal_params",
    "TransactionLineItemListParams": "stripe.params.tax._transaction_line_item_list_params",
    "TransactionListLineItemsParams": "stripe.params.tax._transaction_list_line_items_params",
    "TransactionRetrieveParams": "stripe.params.tax._transaction_retrieve_params",
}
if not TYPE_CHECKING:

    def __getattr__(name):
        try:
            return getattr(
                import_module(_submodules[name]),
                name,
            )
        except KeyError:
            raise AttributeError(f"cannot import '{name}' from '{__name__}'")
