# -*- coding: utf-8 -*-
# File generated from our OpenAPI spec
from stripe._stripe_object import StripeObject
from typing import ClassVar, Optional
from typing_extensions import Literal


class PaymentRetrySignal(StripeObject):
    """
    The PaymentRetrySignal resource represents a single retry recommendation
    generated by the ML scoring model.
    """

    OBJECT_NAME: ClassVar[Literal["v2.signals.payment_retry_signal"]] = (
        "v2.signals.payment_retry_signal"
    )

    class Recommendation(StripeObject):
        action: Literal["give_up", "retry_now", "wait"]
        """
        The recommended action to take.
        """
        reason: str
        """
        Human-readable reason for the recommendation.
        """

    created: str
    """
    When this signal was created.
    """
    evaluation: str
    """
    The evaluation that generated this signal.
    """
    id: str
    """
    Unique identifier for the signal.
    """
    livemode: bool
    """
    Has the value `true` if the object exists in live mode or the value `false` if the object exists in test mode.
    """
    object: Literal["v2.signals.payment_retry_signal"]
    """
    String representing the object's type. Objects of the same type share the same value of the object field.
    """
    payment_intent: Optional[str]
    """
    The payment intent this signal relates to.
    """
    payment_record: str
    """
    The payment record this signal relates to.
    """
    recommendation: Recommendation
    """
    The retry recommendation.
    """
    _inner_class_types = {"recommendation": Recommendation}
